name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    # Step 3: Cache Go modules for faster builds
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Step 4: Download dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 5: Build the project
    - name: Build
      run: go build -v ./...

    # Step 6: Run tests
    - name: Test
      run: go test -v ./...
